### ISSUE TITLE
Need smart phone and tablet support.

### ISSUE THREAD

**Issue by soloradish** [lorien/user_agent#2]

**Comment by pawelmhm** [comment]
mobile user agent support is probably not terribly difficult to provide. Chrome for Android documentation is here: https://developer.chrome.com/multidevice/user-agent Firefox on IoS https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Firefox_for_iOS adding mobile is probably matter of adding platforms here https://github.com/lorien/user_agent/blob/master/user_agent/base.py#L72 Probably there will be also need to add some fake device identifieriers seems like most mobile user-agents add information about device manufacturer.
