### ISSUE TITLE
Chrome versions outdated

### ISSUE THREAD

**Issue by adrianmeraz** [lorien/user_agent#30]
Since the package doesn't pull in outside data, how often will the version numbers be updated? I understand forking may be a valid strategy, but maybe not. For example, in base.py, I see these tuples:

FIREFOX_VERSION = (
    ('45.0', datetime(2016, 3, 8)),
    ('46.0', datetime(2016, 4, 26)),
    ('47.0', datetime(2016, 6, 7)),
    ('48.0', datetime(2016, 8, 2)),
    ('49.0', datetime(2016, 9, 20)),
    ('50.0', datetime(2016, 11, 15)),
    ('51.0', datetime(2017, 1, 24)),
)
CHROME_BUILD = (
    (49, 2623, 2660), # 2016-03-02
    (50, 2661, 2703), # 2016-04-13
    (51, 2704, 2742), # 2016-05-25
    (52, 2743, 2784), # 2016-07-20
    (53, 2785, 2839), # 2016-08-31
    (54, 2840, 2882), # 2016-10-12
    (55, 2883, 2923), # 2016-12-01
    (56, 2924, 2986), # 2016-12-01
)
IE_VERSION = (
    # (numeric ver, string ver, trident ver) # release year
    (8, 'MSIE 8.0', '4.0'), # 2009
    (9, 'MSIE 9.0', '5.0'), # 2011
    (10, 'MSIE 10.0', '6.0'), # 2012
    (11, 'MSIE 11.0', '7.0'), # 2013
)

**Comment by lorien** [comment]
> how often will the version numbers be updated? 
Like once per 2-3 years lol :))
Ok, I've updated google chrome builds list in 69e2b72c2d4ad00b667625bb1537fc5228b092c0
