### ISSUE TITLE
Updating base.py

### ISSUE THREAD

**Issue by userbox020** [lorien/user_agent#33]
Im trying to update the Chrome Build version on the base.py 
But Im having code errors, can you tell me please what this number means?

![image](https://user-images.githubusercontent.com/47074021/98004263-52c72100-1db5-11eb-8092-cc59cc3db1c9.png)

**Comment by lorien** [comment]
Hey. There is browser releases history links at top of base.py
Following the https://en.wikipedia.org/wiki/Google_Chrome_release_history you get a table.
First column is a build "X.0.Y", second column is date of release.
List 'CHROME_BUILDS` contains records for stable google builds, 2nd and 3rd number in each list item means lower and upper border of range to generate random number. So, `(56, 2924, 2986)` could generate random build in range from "56.0.2924" to "56.0.2986"

**Comment by lorien** [comment]
Never mind. I have realized my way of generating chrome build version is invalid. I think the most simple and smart way is just to use top frequent chrome builds from access log of popular website. I have added some chrome builds I have parsed from september/october access of one of my websites.
