### ISSUE TITLE
add some argument to generate_user_agent() to generate only recent versions of browsers

### ISSUE THREAD

**Issue by pawelmhm** [lorien/user_agent#8]
Seems like some websites are not happy with outdated user agents, e.g.

```
curl -vk "https://www.jdsports.co.uk/" -H "User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1910.0 Safari/537.36" -H "Accept-Language: en-US,en;q=0.8,pl;q=0.6" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Connection: keep-alive" --compressed > /dev/null
```

results in

```
> GET / HTTP/1.1
> Host: www.jdsports.co.uk
> Accept-Encoding: deflate, gzip
> User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1910.0 Safari/537.36
> Accept-Language: en-US,en;q=0.8,pl;q=0.6
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Connection: keep-alive
> 
< HTTP/1.1 403 Forbidden
* Server AkamaiGHost is not blacklisted
```

This uses very old user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1910.0 Safari/537.36.

If I "upgrade" my user agent to most recent chrome I get 200 OK:

```
curl -vk "https://www.jdsports.co.uk/" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" -H "Accept-Language: en-US,en;q=0.8,pl;q=0.6" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Connection: keep-alive" --compressed > /dev/null
```

response is:

```
GET / HTTP/1.1
> Host: www.jdsports.co.uk
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
> Accept-Language: en-US,en;q=0.8,pl;q=0.6
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Connection: keep-alive
> 
< HTTP/1.1 200 OK
< Content-Encoding: gzip
```

This is not first time I'm seeing behavior like this. There are also websites that do user agent checks server side and show some irritating messages to users about necessity of upgrading browsers. They should do this with JavaScript, but sometimes they do it server side and return different responses, which can confuse spider.

My idea is to either: limit number of ua versions to most recent by default. Or just add some argument that will specify some range of version numbers to go back to, e.g. range(5) would return only 5 most recent versions of Chrome.

**Comment by pawelmhm** [comment]
actually it may also be incorrect user agent string. When I test with User agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.0 Safari/537.36` I get response ok. The difference is between `Chrome/34.0.1847.0` and `Chrome/34.0.1910.0`. Second form causes 403, first one [is documented in release history](https://en.wikipedia.org/wiki/Google_Chrome_version_history) and works fine. Looking at source code we do something like this: randint(build[1], build[2]). Is that ok @lorien ? Are you sure Chrome actually picks up something between these two minor version numbers? Is it documented somewhere in Chrome development docs?

**Comment by lorien** [comment]
I do not think `ranges(5)` makes sense because it would define different time range for different browsers e.g. five IE versions (whatever version means) would be 6 months, five Firefox versions would be two months.

The only solution from my point of view is to keep the version list up to date and remove versions which are deprecated. What timeout your suggest to remove deprecated version?

**Comment by pawelmhm** [comment]
Actually this bug I mentioned may be caused by other thing see next comment about chrome build range. 

re recent versions, looking at this chart here: https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0&qptimeframe=M it seems that less than 1% of all users use chrome below 45, according to release history it was released in 09 2015. Not surprisingly people use auto-update and almost everyone use recent versions. For Firefox less that 0.3% use 40 released match 2015. So maybe 1.5 year timeframe for versions? For IE rules are different because of lack of auto-update.
